[lib]
crate-type = ["cdylib"]

[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
j4rs = "0.15"
j4rs_derive = "0.1"
lazy_static = "1.4.0"
